site_name: Fast robust meshing
site_url: 'https://wildmeshing.github.io/'
repo_name: 'wildmeshing'
repo_url: 'https://github.com/wildmeshing/wildmeshing-toolkit'
edit_uri: '../https://github.com/wildmeshing/wildmeshing-toolkit/edit/doc/doc/'
site_description: "Fast robust meshing"
# strict: true
docs_dir: 'doc'
remote_branch: 'main'
theme:
  name: material
  custom_dir: 'doc/theme'
  favicon: 'favicon.ico'
  icon:
    logo: material/library
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "cyan"
      accent: "indigo"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "blue"
      accent: "deep purple"
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.expand
    - search.suggest
    - search.highlight
extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/wildmeshing/wildmeshing-toolkit'
extra_css:
  - theme/extra.css
markdown_extensions:
  - codehilite
  - footnotes
  - admonition
  - toc:
      permalink: true
  - markdown.extensions.smarty
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      repo_url_shortener: true
      user: wildmeshing
      repo: wildmeshing
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - mknotebooks:
      execute: true
      preamble: "doc/plot_to_md.py"
      timeout: -1
  - git-revision-date
  - search
  - mkdocs-jupyter:
      ignore_h1_titles: True
      include_source: True
  - include-markdown
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML"
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Home: index.md
  - Toolkit:
    - Home: toolkit.md
    - Json: json_defaults_and_spec.md
    - Docs: https://wildmeshing.github.io/wildmeshing-toolkit/index.html
  - TetWild: tetwild.md
  - fTetWild: ftetwild.md
  - TriWild: triwild.md
  - Python:
    - Home: python.md
    - Notebook: wildmeshing-notebook.ipynb
