name: Build Website

on:
  workflow_dispatch:
  push:
    branches:
      - doc

permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.11.3"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Generate JSON Spec Documentation
        run: |
          git clone --depth=1 https://github.com/wildmeshing/wildmeshing-toolkit.git toolkit
          git clone --depth=1 https://github.com/geometryprocessing/json-spec-engine.git
          pip install -r ./json-spec-engine/requirements.txt
          ls
          python generate_doc.py
          cp ./toolkit/LICENSE ./toolkit/_license.txt

      - name: Deploy MkDocs
        run: mkdocs gh-deploy --force
